name = "drishtikon"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/gohugoio/gohugoioTheme"

# If you have a running demo of the theme.
demosite = "https://gohugo.io"

tags = ["blog", "academic", "photos"]
features = ["some", "awesome", "features"]

# If the theme has a single author
[author]
    name = "Kishen Narayan"
    homepage = "kishenarayan.github.io"

