name = "drishtikon"
languageCode = "en-us"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/gohugoio/gohugoioTheme"

# If you have a running demo of the theme.
demosite = "https://gohugo.io"

tags = ["blog", "academic", "photos"]
features = ["some", "awesome", "features"]

# If the theme has a single author
[author]
    name = "Kishen Narayan"
    homepage = "kishenarayan.github.io"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    # Uncomment if you have a logo image
    # logo = "/images/logo.png"

    # Profile section for homepage
    profilePhoto = "/images/pfp.jpg"
    profileDescription = """Welcome to drishtikon (*perspective*). Stay a while! Drishtikon is a simple, minimal, [Hugo](https://gohugo.io/) theme that takes inspiration from Andrew Hwan Park's [Brutalist Blog](https://hw4n.com/brutalist-blog/) and Tyler McRobert's [Bridget](https://tylermcrobert.com/bridget-baker). Additionally, this theme uses the [Inter](https://rsms.me/inter/) typeface originally developed by Rasmus Andersson."""
    github = "https://github.com/yourusername"
    email = "mailto:your.email@example.com"
    math = true

[menu]
    [[menu.main]]
        name = "posts"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        name = "writings"
        url = "/writings/"
        weight = 20
    [[menu.main]]
        name = "photos"
        url = "/photos/"
        weight = 30


